#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOSQL
CREATE USER ${NEWAPI_DB_USER} WITH PASSWORD '${NEWAPI_DB_PASSWORD}';
CREATE DATABASE ${NEWAPI_DB_NAME} OWNER ${NEWAPI_DB_USER};
CREATE USER ${SUB2API_DB_USER} WITH PASSWORD '${SUB2API_DB_PASSWORD}';
CREATE DATABASE ${SUB2API_DB_NAME} OWNER ${SUB2API_DB_USER};
EOSQL
